name: First-workflow
on : push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test Code
      run: npm run test
    - name: npm run build
      run: npm run build
    - name: Deploy code
      run: echo "Deploying...."
