name: Notify Slack on SQL Changes

on:
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, closed, reopened]
  workflow_dispatch:

jobs:
  pr-event:
    uses: Ashakkena/remoteworkflow/.github/workflows/test.yml@main
