name: Notify Slack on SQL Changes

on:
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, closed, reopened]
  workflow_dispatch:
    inputs:
      environments:
        required: true
        options:
          - dev
          - int

jobs:
  pr-event:
    uses: Ashakkena/remoteworkflow/.github/workflows/test.yml@main
    secrets: inherit

